import { AuthProvider } from "./context/AuthContext";
import "./globals.css";
import type { Metadata } from "next";
import { config } from '@fortawesome/fontawesome-svg-core';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest:"/web.manifest"
};



config.autoAddCss = false; // Disable auto-injection of FontAwesome CSS
import Navbar  from "@/app/component/Navbar";
import RootLayoutClient from "./Root";
import LoadingBar from "@/app/component/LoadingBar";


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
    <html lang="en">
      <body className="bg-white">
     
        <Navbar />
       
       <RootLayoutClient>
       <LoadingBar />
        {children}
        </RootLayoutClient> 
      </body>
    </html>
    </AuthProvider>
  );
}
